version: "3.0"

services:
    server:
        build:
            context: "./server"
            dockerfile: "Dockerfile.${ENV:-default}"
        restart: unless-stopped
        environment:
            - NODE_ENV=production

            - HMAC_SECRET=s3cr3t # Change me

            - HOST=0.0.0.0
            - PORT=5000

            - TORRENT_MAX_WORKERS=4
            - TORRENT_PATH=./torrents
            - TORRENT_MAX_RATIO=2
            - TORRENT_PRUNE_INTERVAL=900000 # 15 mins
            - TORRENT_EXPIRATION=604800000 # 7 days
        volumes:
            - ./data:/app/torrents
        network_mode: "host"
